### PR TITLE
fixes tooltip issue #193

### PR DESCRIPTION
**Pull request by yochannah**
This fixes an issue where tooltips were appearing unstyled. After investigation this was a combination of two issues - one that we were missing a tiny bit of CSS after upgrading bootstrap, the other that jQuery UI's `tooltip()` method was overriding bootstrap's `tooltip()` method (argh). Both have been fixed. 

To test: 

- clone this pr
- build using `npm run dev`
- go to http://localhost:9000/test/test-load-from-global.html and confirm that tooltips for the column headers display es expected.

### CODE REVIEW

**Comment by yochannah** [comment]
sorry - by tooltips I meant the on-hover effect that occurs when you hold your mouse over the icons, not the on-click behaviour. See the black area in this screenshot: 

column headers with tooltip enabled

The other issues you mention - not closing - we should make another issue for this, and like you mentioned, the column summary is reported as #190 I think

**Comment by uosl** [comment]
Looks like the Less changes are unnecessary if we do the fix I mentioned in https://github.com/intermine/im-tables/pull/191#issuecomment-571517650. Then updating `shim.js` to require bootstrap after jquery is enough to fix the tooltips.

**Comment by yochannah** [comment]
I just noticed that my screenshot didn't have the tooltip in  it - thanks for figuring out what I meant anyway 🤦‍♂

**Comment by uosl** [comment]
I reverted the changes to the CSS/Less files (everything other than `shim.js`).

Please merge once you've reviewed #199.

**Comment by uosl** [comment]
Closing as this will be merged via #201 instead due to recaffeination.

**Pull request closed without merging**
