### PR TITLE
Adding Cypress tests to the project

### PR DESCRIPTION
**Pull request by Manasa2850**
Solves Issue #224 
I have tested in Firefox and Google Chrome
I have written tests for:
- Checking if the table loads correctly `loadtable_spec.js`
- Checking if the pagination controls are as per requirement `pagination_spec.js`
- Checking if code generation works properly `codeGeneration_spec.js`
- Checking if all features of column manager is present and works properly `columnManager_spec.js`

### CODE REVIEW

**Comment by Manasa2850** [comment]
`loadtable_spec.js` is the file which contains tests to check if the table loads correctly.
@yochannah Currently I've deleted the files in `cypress/integration/examples` because these files are not needed. Let me know if I should include them.

**Comment by Manasa2850** [comment]
These are the tests to check if the table loads properly
cypressTest1

**Comment by Manasa2850** [comment]
`pagination_spec.js` has tests for pagination controls.

Screenshot of the test:
cypressTest2

**Review by heralden — APPROVED** [review]
I apologise for the very late feedback!

These are a great set of initial tests. Thank you for your work! :+1:

**Pull request merged**
